In [2]:
import numpy as np

In [3]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [5]:
array_list = np.array(object = list_)

In [6]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
## Q1

In [8]:
"""A list in Python is a built-in data type that stores a collection of items. It is a mutable, ordered sequence of elements and can contain elements of different data types."""

"""An array in Python typically refers to the array module provided by the NumPy library. It is a data structure that stores homogeneous elements and provides efficient numerical operations. Arrays in NumPy have a fixed size upon creation and offer various mathematical operations optimized for performance."""


'An array in Python typically refers to the array module provided by the NumPy library. It is a data structure that stores homogeneous elements and provides efficient numerical operations. Arrays in NumPy have a fixed size upon creation and offer various mathematical operations optimized for performance.'

In [11]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list= np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [12]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [13]:
list_

['1', '2', '3', '4', '5']

In [14]:
## Q2

In [15]:
import numpy as np

In [19]:
list_=[1,2,3.14,True,"Hello"]
array_list = np.array([1,2,6,5,3])

print("Data types of each elements in list_")
for element in list_:
    print(type(element))
    
print("Data types of each elements in array_list")
for elements in array_list:
    print(type(elements))

Data types of each elements in list_
<class 'int'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>
Data types of each elements in array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [20]:
## Q3

In [ ]:
import numpy as np

In [21]:
list_=[1,2,3.14,True,"Hello"]
array_list = np.array(object = list_, dtype=int)

print("Data types of each elements in list_")
for element in list_:
    print(type(element))
    
print("\nData types of each elements in array_list")
for elements in array_list:
    print(type(elements))

ValueError: invalid literal for int() with base 10: 'Hello'

In [22]:
## Q4

In [23]:
import numpy as np

In [24]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [25]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [26]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
print(num_array.shape)

(2, 3)


In [28]:
print(num_array.size)

6


In [29]:
## Q5

In [30]:
import numpy as np

In [33]:
arr = np.zeros([3,3])

print(arr.size)

print(arr.shape)

9
(3, 3)


In [34]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
## Q6

In [36]:
import numpy as np

In [40]:
identity_matrix = np.identity(5 , dtype=int)

In [41]:
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [42]:
print(identity_matrix.shape)

(5, 5)
